#!/usr/bin/env python3
"""Generates DOCUMENTATION/application/CODE_TREE.html from CODE_TREE.md.

CODE_TREE.md is the single source: edit it, then run
    python3 tools/code_tree_html.py
The HTML is self-contained (no network, works offline) with collapsible folders and search.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "DOCUMENTATION" / "application" / "CODE_TREE.md"
TARGET = ROOT / "DOCUMENTATION" / "application" / "CODE_TREE.html"

TREE_CHARS = set("│├└─ ")
FILE_NAMES = {"CMakeLists.txt", ".gitignore", "CLAUDE.md", "README.md"}
FILE_EXTENSIONS = (".hpp", ".cpp", ".md", ".txt", ".py", ".html", ".cmake")


def code_blocks(text):
    # Fences must start a line, so backticks inside a description can't end a block early.
    return re.findall(r"^```text\n(.*?)^```[ \t]*$", text, flags=re.S | re.M)


def kind_of(label):
    first = label.split(" ")[0]
    if label.endswith("/"):
        return "dir"
    if first in FILE_NAMES or first.endswith(FILE_EXTENSIONS):
        return "file"
    for prefix, kind in (("ns ", "ns"), ("class ", "class"), ("struct ", "struct"), ("enum ", "enum"),
                         ("fn ", "fn"), ("using ", "alias"), ("static ", "static"), ("target ", "target")):
        if label.startswith(prefix):
            return kind
    if label.startswith(".") or re.match(r"^~?[A-Z]\w*\(", label):
        return "method"  # members, constructors, destructors
    if re.match(r"^[a-z_][\w<>:]*\(", label):
        return "fn"  # internal helpers listed without the "fn" prefix
    if re.match(r"^[A-Z][A-Za-z]+\.(\*|[A-Z])", label) or label.startswith("TEST"):
        return "test"
    return "item"


def parse_tree(block):
    """Turns the box-drawing tree into nested {label, desc, kind, tags, children} nodes."""
    root = None
    stack = []  # (depth, node)
    last = None
    for raw in block.rstrip("\n").split("\n"):
        if not raw.strip() or set(raw) <= TREE_CHARS:
            continue
        start = next(i for i, c in enumerate(raw) if c not in TREE_CHARS)
        prefix, content = raw[:start], raw[start:].rstrip()
        is_node = root is None or "├── " in prefix[-4:] or "└── " in prefix[-4:]
        if not is_node:
            # A continuation line: more description for the node above.
            if last is not None:
                last["desc"] = (last["desc"] + " " + content.strip()).strip()
            continue
        match = re.match(r"^(.*?)\s{2,}(.*)$", content)
        label, desc = (match.group(1), match.group(2)) if match else (content, "")
        node = {"label": label.strip(), "desc": desc.strip(), "children": []}
        node["kind"] = kind_of(node["label"])
        node["tags"] = [t for t in ("private", "internal") if f"({t})" in node["label"] + " " + node["desc"]]
        depth = 0 if root is None else len(prefix) // 4
        if root is None:
            root = node
            stack = [(0, node)]
        else:
            while stack and stack[-1][0] >= depth:
                stack.pop()
            stack[-1][1]["children"].append(node)
            stack.append((depth, node))
        last = node
    return root


def count(node, kinds):
    own = 1 if node["kind"] in kinds else 0
    return own + sum(count(c, kinds) for c in node["children"])


def main():
    text = SOURCE.read_text(encoding="utf-8")
    blocks = code_blocks(text)
    if len(blocks) < 2:
        sys.exit("CODE_TREE.md must contain the tree and the call-flow ```text blocks")
    tree = parse_tree(blocks[0])
    updated = re.search(r"Last updated: (.*)", text)
    stats = {
        "files": count(tree, {"file"}),
        "types": count(tree, {"class", "struct", "enum", "alias"}),
        "functions": count(tree, {"fn", "method", "static"}),
        "tests": sum(int(n) for n in re.findall(r"(\d+) TESTs", text)),
    }
    data = {
        "tree": tree,
        "flow": blocks[1].rstrip("\n"),
        "updated": updated.group(1).strip() if updated else "",
        "stats": stats,
    }
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    TARGET.write_text(TEMPLATE.replace("__DATA__", payload), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}: {stats}")


TEMPLATE = r"""<!doctype html>
<!-- GENERATED by tools/code_tree_html.py from CODE_TREE.md. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>hoardor code tree</title>
<style>
  :root {
    --bg: #f7f6f2; --panel: #ffffff; --text: #1d1d1b; --muted: #6b6a63; --line: #e2e0d8;
    --accent: #2f5d50; --mark: #ffe58a;
    --dir: #6b5b2e; --file: #3b4a6b; --ns: #7a3e6d; --type: #2f5d50; --fn: #8a4b14;
    --test: #4a6b2f; --alias: #555; --target: #6b2f2f;
    --chip-bg: rgba(0,0,0,.05);
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #151614; --panel: #1d1f1c; --text: #e8e6df; --muted: #9a988f; --line: #30322e;
      --accent: #8cc7b2; --mark: #6b5a12;
      --dir: #d8c07a; --file: #9db4e0; --ns: #d99acb; --type: #8cc7b2; --fn: #e8a76a;
      --test: #a9cf86; --alias: #b5b5b5; --target: #e09a9a;
      --chip-bg: rgba(255,255,255,.07);
    }
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text);
         font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
  .wrap { max-width: 1180px; margin: 0 auto; padding: 24px 16px 64px; }
  h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -.01em; }
  .sub { color: var(--muted); margin: 0 0 16px; }
  .stats { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
  .stat { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 6px 12px; }
  .stat b { font-variant-numeric: tabular-nums; }
  .bar { position: sticky; top: 0; z-index: 2; background: var(--bg); padding: 10px 0;
         display: flex; flex-wrap: wrap; gap: 8px; align-items: center; border-bottom: 1px solid var(--line); }
  input[type=search] { flex: 1 1 260px; min-width: 0; padding: 8px 12px; font: inherit; color: var(--text);
         background: var(--panel); border: 1px solid var(--line); border-radius: 8px; }
  button { font: inherit; padding: 7px 12px; border-radius: 8px; border: 1px solid var(--line);
           background: var(--panel); color: var(--text); cursor: pointer; }
  button:hover { border-color: var(--accent); }
  .legend { display: flex; flex-wrap: wrap; gap: 6px; margin: 12px 0 8px; font-size: 13px; color: var(--muted); }
  .tree { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 12px 8px; overflow-x: auto; }
  ul { list-style: none; margin: 0; padding-left: 18px; border-left: 1px solid var(--line); }
  .tree > ul { border-left: 0; padding-left: 4px; }
  li { margin: 1px 0; }
  details > summary { list-style: none; cursor: pointer; }
  details > summary::-webkit-details-marker { display: none; }
  .row { display: flex; gap: 8px; align-items: baseline; padding: 2px 6px; border-radius: 6px; }
  .row:hover { background: var(--chip-bg); }
  .twisty { width: 12px; flex: 0 0 12px; color: var(--muted); font-size: 11px; }
  details[open] > summary .twisty::before { content: "▾"; }
  details:not([open]) > summary .twisty::before { content: "▸"; }
  .label { font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; font-size: 13.5px; white-space: nowrap; }
  .desc { color: var(--muted); font-size: 13.5px; }
  .badge { font-size: 11px; padding: 0 6px; border-radius: 999px; background: var(--chip-bg);
           font-family: ui-monospace, monospace; white-space: nowrap; }
  .k-dir .label, .b-dir { color: var(--dir); } .k-dir .label { font-weight: 600; }
  .k-file .label, .b-file { color: var(--file); }
  .k-ns .label, .b-ns { color: var(--ns); }
  .k-class .label, .k-struct .label, .k-enum .label, .b-class, .b-struct, .b-enum { color: var(--type); }
  .k-fn .label, .k-method .label, .k-static .label, .b-fn, .b-method, .b-static { color: var(--fn); }
  .k-test .label, .b-test { color: var(--test); }
  .k-alias .label, .b-alias { color: var(--alias); }
  .k-target .label, .b-target { color: var(--target); }
  .tag { font-size: 11px; color: var(--muted); border: 1px dashed var(--line); border-radius: 4px; padding: 0 4px; }
  mark { background: var(--mark); color: inherit; border-radius: 2px; }
  .hidden { display: none; }
  h2 { font-size: 17px; margin: 28px 0 8px; }
  pre { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 12px;
        overflow-x: auto; font-size: 13px; line-height: 1.45; }
  .empty { color: var(--muted); padding: 8px 12px; }
  @media (max-width: 640px) { .row { flex-wrap: wrap; } .label { white-space: normal; word-break: break-word; } }
</style>
</head>
<body>
<div class="wrap">
  <h1>hoardor code tree</h1>
  <p class="sub" id="updated"></p>
  <div class="stats" id="stats"></div>
  <div class="bar">
    <input type="search" id="q" placeholder="Search files, types, functions, tests…  (press / to focus)" autocomplete="off">
    <button id="expand">Expand all</button>
    <button id="collapse">Collapse all</button>
  </div>
  <div class="legend" id="legend"></div>
  <div class="tree" id="tree"></div>
  <h2>Call flow of a Sync</h2>
  <pre id="flow"></pre>
</div>
<script>
const DATA = __DATA__;
const KINDS = { dir: "folder", file: "file", ns: "namespace", class: "class", struct: "struct", enum: "enum",
                alias: "type alias", fn: "function", method: "member", static: "static", test: "tests", target: "target" };

document.getElementById("updated").textContent =
  "Generated from CODE_TREE.md · last updated " + DATA.updated;
const stats = document.getElementById("stats");
for (const [k, v] of Object.entries(DATA.stats)) {
  const s = document.createElement("div");
  s.className = "stat";
  s.innerHTML = "<b></b> " + k;
  s.querySelector("b").textContent = v;
  stats.appendChild(s);
}
const legend = document.getElementById("legend");
for (const [k, name] of Object.entries(KINDS)) {
  const b = document.createElement("span");
  b.className = "badge b-" + k;
  b.textContent = name;
  legend.appendChild(b);
}
for (const t of ["private", "internal"]) {
  const b = document.createElement("span");
  b.className = "tag";
  b.textContent = t;
  legend.appendChild(b);
}
document.getElementById("flow").textContent = DATA.flow;

// Build the DOM once; search only toggles classes and <details open>.
const entries = [];  // { node, li, details, labelEl, descEl, parent }
function build(node, depth, parent) {
  const li = document.createElement("li");
  li.className = "k-" + node.kind;
  const row = document.createElement("div");
  row.className = "row";
  const twisty = document.createElement("span");
  twisty.className = "twisty";
  const label = document.createElement("span");
  label.className = "label";
  label.textContent = node.label;
  const desc = document.createElement("span");
  desc.className = "desc";
  desc.textContent = node.desc;
  row.append(twisty, label);
  if (node.kind !== "item" && node.kind !== "dir" && node.kind !== "file") {
    const badge = document.createElement("span");
    badge.className = "badge b-" + node.kind;
    badge.textContent = KINDS[node.kind];
    row.append(badge);
  }
  for (const t of node.tags) {
    const tag = document.createElement("span");
    tag.className = "tag";
    tag.textContent = t;
    row.append(tag);
  }
  row.append(desc);
  const entry = { node, li, details: null, labelEl: label, descEl: desc, parent };
  entries.push(entry);
  if (node.children.length) {
    const details = document.createElement("details");
    details.open = depth < 2;
    const summary = document.createElement("summary");
    summary.appendChild(row);
    const ul = document.createElement("ul");
    for (const c of node.children) ul.appendChild(build(c, depth + 1, entry));
    details.append(summary, ul);
    li.appendChild(details);
    entry.details = details;
  } else {
    li.appendChild(row);
  }
  return li;
}
const rootUl = document.createElement("ul");
rootUl.appendChild(build(DATA.tree, 0, null));
const treeEl = document.getElementById("tree");
treeEl.appendChild(rootUl);
const empty = document.createElement("div");
empty.className = "empty hidden";
empty.textContent = "Nothing matches.";
treeEl.appendChild(empty);

function highlight(el, text, q) {
  el.textContent = "";
  if (!q) { el.textContent = text; return; }
  const lower = text.toLowerCase();
  let i = 0, at;
  while ((at = lower.indexOf(q, i)) !== -1) {
    el.append(text.slice(i, at));
    const m = document.createElement("mark");
    m.textContent = text.slice(at, at + q.length);
    el.append(m);
    i = at + q.length;
  }
  el.append(text.slice(i));
}

const defaultOpen = new Map(entries.filter(e => e.details).map(e => [e, e.details.open]));
function search(raw) {
  const q = raw.trim().toLowerCase();
  let any = false;
  for (const e of entries) {
    highlight(e.labelEl, e.node.label, q);
    highlight(e.descEl, e.node.desc, q);
  }
  if (!q) {
    for (const e of entries) e.li.classList.remove("hidden");
    for (const [e, open] of defaultOpen) e.details.open = open;
    empty.classList.add("hidden");
    return;
  }
  const visible = new Set();
  for (const e of entries) {
    const hit = (e.node.label + " " + e.node.desc).toLowerCase().includes(q);
    if (!hit) continue;
    any = true;
    // A match shows itself, everything under it, and the path above it.
    const stack = [e];
    while (stack.length) {
      const x = stack.pop();
      visible.add(x);
      for (const y of entries) if (y.parent === x) stack.push(y);
    }
    for (let p = e.parent; p; p = p.parent) visible.add(p);
  }
  for (const e of entries) {
    e.li.classList.toggle("hidden", !visible.has(e));
    if (e.details) e.details.open = visible.has(e);
  }
  empty.classList.toggle("hidden", any);
}

const input = document.getElementById("q");
input.addEventListener("input", () => search(input.value));
document.addEventListener("keydown", ev => {
  if (ev.key === "/" && document.activeElement !== input) { ev.preventDefault(); input.focus(); }
  if (ev.key === "Escape" && document.activeElement === input) { input.value = ""; search(""); }
});
document.getElementById("expand").onclick = () => { for (const e of entries) if (e.details) e.details.open = true; };
document.getElementById("collapse").onclick = () => {
  for (const e of entries) if (e.details) e.details.open = e.parent === null;
};
</script>
</body>
</html>
"""

if __name__ == "__main__":
    main()
